### PR TITLE
Fix improper layout and focus events on ledger form

### LINKED ISSUE #13: (Desktop) Improper layouts on ledger component

### PR DESCRIPTION
**Pull request by brainkid92**
closes #13

### CODE REVIEW

File: projects/auditplus-desktop/src/app/master/account-info/ledger/ledger-form/ledger-form.component.ts [hunk 1]
```diff
@@ -88,6 +88,7 @@ export class LedgerFormComponent implements OnInit, OnChanges {
 
   disabledLedgerForm() {
     this.ledgerFormEnabled = false;
+    console.log(this.ledgerFormEnabled);
```
Comment (hchockarprasad) [inline projects/auditplus-desktop/src/app/master/account-info/ledger/ledger-form/ledger-form.component.ts]: Remove console log statement
